import { SBT_LEVEL } from '@/constants/enum';

export const DEV_BADGES = {
  [SBT_LEVEL.ORANGE]: {
    asset: 'https://cdn.galaxy.eco/galaxy/assets/projecttwelve/1653656759076802901.gif',
    asset256: 'https://cdn1.p12.games/airdrop/badge/dev_orange_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/dev_badge_orange.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/dev_badge_orange.png',
    claim: 'https://galxe.com/P12/campaign/GCt9JUUJCJ',
    title: 'P12 Genesis Badge [Orange Rarity]',
    rarity: 'Legendary',
    color: 'text-legendary',
  },
  [SBT_LEVEL.PURPLE]: {
    asset: 'https://cdn.galaxy.eco/galaxy/assets/projecttwelve/1653654265642526889.gif',
    asset256: 'https://cdn1.p12.games/airdrop/badge/dev_purple_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/dev_badge_purple.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/dev_badge_purple.png',
    claim: 'https://galxe.com/P12/campaign/GCteJUUM7z',
    title: 'P12 Genesis Badge [Purple Rarity]',
    rarity: 'Epic',
    color: 'text-epic',
  },
  [SBT_LEVEL.BLUE]: {
    asset: 'https://cdn.galaxy.eco/galaxy/assets/projecttwelve/1653653761673395155.gif',
    asset256: 'https://cdn1.p12.games/airdrop/badge/dev_blue_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/dev_badge_blue.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/dev_badge_blue.png',
    claim: 'https://galxe.com/P12/campaign/GCi9CUUrni',
    title: 'P12 Genesis Badge [Blue Rarity]',
    rarity: 'Rare',
    color: 'text-rare',
  },
  [SBT_LEVEL.GREEN]: {
    asset: 'https://cdn.galaxy.eco/galaxy/assets/projecttwelve/1653653545770629768.gif',
    asset256: 'https://cdn1.p12.games/airdrop/badge/dev_green_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/dev_badge_green.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/dev_badge_green.png',
    claim: 'https://galxe.com/P12/campaign/GCV4JUU7eR',
    title: 'P12 Genesis Badge [Green Rarity]',
    rarity: 'Uncommon',
    color: 'text-uncommon',
  },
  [SBT_LEVEL.WHITE]: {
    asset: 'https://cdn.galxe.com/galaxy/p12/154badfe-3f5d-44b2-883f-457fdd70227a.gif',
    asset256: 'https://cdn1.p12.games/airdrop/badge/dev_white_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/dev_badge_white.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/dev_badge_white.png',
    claim: 'https://galxe.com/P12/campaign/GCoj1UcDS8',
    title: 'P12 Genesis Badge [White Rarity]',
    rarity: 'Common',
    color: 'text-common',
  },
  [SBT_LEVEL.REKT]: {
    asset: 'https://cdn.galxe.com/galaxy/p12/3412087f-201d-4acf-b38f-2bbf2986cf51.gif',
    asset256: 'https://cdn1.p12.games/airdrop/badge/dev_rekt_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/dev_badge_rekt.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/dev_badge_rekt.png',
    claim: 'https://galxe.com/P12/campaign/GCw9mUctpb',
    title: 'P12 Genesis Badge [Rekt Rarity]',
    rarity: 'Common',
    color: 'text-common',
  },
};

export const GAMER_BADGES = {
  [SBT_LEVEL.ORANGE]: {
    asset: 'https://cdn1.p12.games/airdrop/badge/gamer_orange.webp',
    asset256: 'https://cdn1.p12.games/airdrop/badge/gamer_orange_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/gamer_badge_orange.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/gamer_badge_orange_2.png',
    claim: 'https://galxe.com/P12/campaign/GCZ74Utyqp',
    title: 'P12 XII-PLORER Badge [Orange Rarity]',
    rarity: 'Legendary',
    color: 'text-legendary',
  },
  [SBT_LEVEL.PURPLE]: {
    asset: 'https://cdn1.p12.games/airdrop/badge/gamer_purple.webp',
    asset256: 'https://cdn1.p12.games/airdrop/badge/gamer_purple_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/gamer_badge_purple.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/gamer_badge_purple_2.png',
    claim: 'https://galxe.com/P12/campaign/GCZm4UtEeE',
    title: 'P12 XII-PLORER Badge [Purple Rarity]',
    rarity: 'Epic',
    color: 'text-epic',
  },
  [SBT_LEVEL.BLUE]: {
    asset: 'https://cdn1.p12.games/airdrop/badge/gamer_blue.webp',
    asset256: 'https://cdn1.p12.games/airdrop/badge/gamer_blue_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/gamer_badge_blue.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/gamer_badge_blue_2.png',
    claim: 'https://galxe.com/P12/campaign/GCuBwUtL6P',
    title: 'P12 XII-PLORER Badge [Blue Rarity]',
    rarity: 'Rare',
    color: 'text-rare',
  },
  [SBT_LEVEL.GREEN]: {
    asset: 'https://cdn1.p12.games/airdrop/badge/gamer_green.webp',
    asset256: 'https://cdn1.p12.games/airdrop/badge/gamer_green_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/gamer_badge_green.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/gamer_badge_green_2.png',
    claim: 'https://galxe.com/P12/campaign/GCrkwUtqiz',
    title: 'P12 XII-PLORER Badge [Green Rarity]',
    rarity: 'Uncommon',
    color: 'text-uncommon',
  },
  [SBT_LEVEL.WHITE]: {
    asset: 'https://cdn1.p12.games/airdrop/badge/gamer_white.webp',
    asset256: 'https://cdn1.p12.games/airdrop/badge/gamer_white_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/gamer_badge_common.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/gamer_badge_common_2.webp',
    claim: 'https://galxe.com/P12/campaign/GCirwUtCCS',
    title: 'P12 XII-PLORER Badge [WHITE Rarity]',
    rarity: 'Common',
    color: 'text-common',
  },
  [SBT_LEVEL.REKT]: {
    asset: 'https://cdn1.p12.games/airdrop/badge/gamer_rekt.webp',
    asset256: 'https://cdn1.p12.games/airdrop/badge/gamer_rekt_256.webp',
    img: 'https://cdn1.p12.games/airdrop/img/gamer_badge_rekt.png',
    imgBig: 'https://cdn1.p12.games/airdrop/img/gamer_badge_rekt_2.webp',
    claim: 'https://galxe.com/P12/campaign/GCuagUtMfG',
    title: 'P12 XII-PLORER Badge [REKT Rarity]',
    rarity: 'Common',
    color: 'text-common',
  },
};

// TypeScript utility function
export const codeUpdate = (): void => {
  console.log('Code updated successfully');
};
